### ISSUE TITLE
Cant use full path in config?

### ISSUE THREAD

**Issue by TomLewis** [eldoriarpg/SchematicBrushReborn#109]
I tried setting a full path in the config for where all my schematics are saved, but its not loading the full path?
`path: /home/username/survival/plugins/WorldEdit/schematics` 

My schematics are not saved in that server, I have a shared schematics folder between multiple servers, surely its not limited to same server folders only?

**Comment by RainbowDashLabs** [comment]
The path is currently relative to the plugin directory of the server. I see three possible solutions.

1. Add a symlink to link to your global schematic directory
2. Try to step up in the hierachie. `../../survival/plugins/WorldEdit/schematics` This might work
3. Wait for me to implement an option to enter abolute paths as a schematic directory.

**Comment by TomLewis** [comment]
I didnt even think to use steps, too tired last night! I will wait until we have a full path.
WorldEdit/Fawe allows full paths, and a few years ago I created a shared schematics folder, which makes moving things between servers very easy! 

Thanks for the fast responce!

**Comment by RainbowDashLabs** [comment]
We are rewriting the saving of presets currently in order to allow saving to a database, which also affects the schematic access a bit.

The change is technically implemented, but it will be released with the storage rewrite.

**Comment by TomLewis** [comment]
Thanks for the update, very much appreciated.

**Comment by RainbowDashLabs** [comment]
@TomLewis The change got released on spigot ^^
