### ISSUE TITLE
UUID variable in schematics folder

### ISSUE THREAD

**Issue by braceyourself07** [eldoriarpg/SchematicBrushReborn#19]
I use the `paths.per-player-schematics: true` setting in FAWE so our schematics folder contain subfolders named after UUIDs of players so that their schematics do not mix.  Is it possible to incorporate an option or feature that we could utilize that in schematic brush reborn?

**Comment by RainbowDashLabs** [comment]
What would be the expected behaviour?
1. Ignore them? 
2. Make them general accessable for everyone without the uuid directory
3. Add the schematics to the search index for individual players, that players can access only their own specific schematics?

**Comment by braceyourself07** [comment]
Yes, number 3.  We have a number of builders who like using the plugin, but many of them work on marketplace content and don't wish to share their schematics with competing builders.  So something where schematic brush could draw from only their own specific schematics would be our ideal configuration.
