### ISSUE TITLE
Add mask option

### ISSUE THREAD

**Issue by ElitoGame** [eldoriarpg/SchematicBrushReborn#23]
Similar to the worldedit /mask feature. e.g. `/sbr ^tree_big*!*@*#"!gold_block"` would paste any matching big trees without gold blocks.

Here's a [link](https://worldedit.enginehub.org/en/latest/usage/general/masks/) to WorldEdits mask page. As for the SBR implementation: # would mark the start of the mask and if the mask is combined of multiple elements, quotation can be used.

I am sure a bunch of people would like this a little more advanced feature, so if you've got some time, it'd be great to have this feature, thanks!

**Comment by RainbowDashLabs** [comment]
I am currently working on the 2.0 version of Schematic Brush.

Just to be clear:

You want to paste a schematic, but remove blocks from the schematic which match a mask, right?

**Comment by ElitoGame** [comment]
Yeah correct, I think it can be pretty useful sometimes =)

**Comment by RainbowDashLabs** [comment]
Heyo I implemented the block filter in 2.0. If you want to test 2.0 and the block filter hit me up on my [discord](https://discord.gg/zRW9Vpu) and I'll send you a beta build ^^
