### ISSUE TITLE
schematicbrush.use not in the wiki for using the plugin in general

### ISSUE THREAD

**Issue by TomLewis** [eldoriarpg/SchematicBrushReborn#359]
Couldn't get the permissions to work, did a luckperms verbose and found `schematicbrush.use` is required to use the plugin, not in the Wiki https://github.com/eldoriarpg/SchematicBrushReborn/wiki/Commands#permissions

Cant edit the wiki! So making a ticket!

**Comment by rainbowdashlabs** [comment]
This permission should actually not exist :D Removed it in the next release. Thanks for reporting c:

**Comment by RedstoneFuture** [comment]
Yes, you can't currently use `/sbr` without this permission or `schematicbrush.*`.

I also had to search for a longer time to find out why my permission setup is not working at SBR.
