### ISSUE TITLE
Survival mechanic when pasting

### ISSUE THREAD

**Issue by RainbowDashLabs** [eldoriarpg/SchematicBrushReborn#87]
Add block consumption for survival mode players.
- Toggleable - default disabled
- Active in only in survival mode
- Bypass permission
- Only paste schematic when player has sufficient blocks in inventory 
- Take blocks from players after pasting

Implemented in [SurvivalSchematicBrush](https://github.com/eldoriarpg/survivalschematicbrush)

**Comment by TomLewis** [comment]
I too would like a survival version of brushes, but slightly different, to work exactly the same as structure boxes.
https://dev.bukkit.org/projects/structure-boxes

Where you can save a schematic(s) onto an item, that can be sold in an admin shop, so then players can buy a pre-made schematic that they can paste once.

**Comment by RainbowDashLabs** [comment]
Why do you need another implementation if there is already exactly one which works like you need it?

The only lacking feature I see there is that it doesnt have a preview of it as it seems.

I implemented the written feature from above in https://github.com/eldoriarpg/survivalschematicbrush. Maybe you can live with this slightly different approach as well. Reimplementing strucure-boxes as a sbr add on seems for me like a completely new plugin, which greatly exceeds my current time budget. Implementing this would also require to rewrite the internal structure of sbr since it is not designed to be used without actual access to the brush configuration interface. However if you have some skilled devs they are free to use our api to implement an add on like this by themself.

**Comment by TomLewis** [comment]
> Why do you need another implementation if there is already exactly one which works like you need it?

StrucutreBoxes has Been abandoned/Not taking feature requests.
There are outstanding issues with it, be nice to have an altearntive so im not stuck when it fully breaks, theres no sight that it will be updated for 1.19 either.
It does not have preview either.

One benefit of taking on this feature is your plugin goes from Creative Staff only plugin, to something that every survival server can use/Mini game can use expanding your audience. 

1. Currently SchematicBrushReborn can only be used by trusted staff members, so its 9 euros to be used by 1-3 people in my case, you have to weigh that up to how much it will get used, I ended up buying with the hope it would be expanded with featues over time.
2. Some use cases you could advertise if you had a way to bind schematics to items:
    - For Movecraft servers, buying pre-made vehicles
    - Normal SMPs, pre made structures that players can buy and place, it would just need to be bound to the items name/lore as there are many shop plugins already.
    - Used in mini games for building things in certain areas, like bridges etc.

I sadly do not have developers at my disposal.

The logic is sadly flawed with the written implementation, as you are limited to the amount of blocks a user has in their inventory, and its a lot of messing around for them to collect everything in a schematic exactly, easier to pass this into in-game currency or other transition so its easier.

**Comment by RainbowDashLabs** [comment]
I will think about it and maybe I can come up with a good and also simple Solution with it. I am always happy to extend SBR with new features or Add-Ons. However this will take some time. Finding a good solution which will ne be thrown over board again after a few changes is very hard and I'd like to think about implementations longer than just go ahead and build something which might work in the first place.

Your request is not declined, but it will take time.

**Comment by RainbowDashLabs** [comment]
This issue is closed since the initial described implementation is done.

Further discussion in #111
