### ISSUE TITLE
Preview not working when skipping schematic

### ISSUE THREAD

**Issue by yannicksuc** [eldoriarpg/SchematicBrushReborn#91]
When placing schematic in my world, if I skip the current schematic the preview desapear until I skip more times and end up going back to the orginal schematic.

Bind a brush to a tool and :
![image](https://user-images.githubusercontent.com/25967079/165082261-7c74eb8b-b283-4f19-95c2-996542c075ca.png)
"f" pressed
![image](https://user-images.githubusercontent.com/25967079/165082334-b4e897e3-1a7e-4bf5-8b03-50cfdc44b7a0.png)
"f" pressed N times 
![image](https://user-images.githubusercontent.com/25967079/165082538-7573c1d1-8acd-4a1a-b59b-890fbb41210b.png)

**Comment by RainbowDashLabs** [comment]
Are you sure that the other schematic do not exceed the maxPreviewSize set in your config?

**Comment by yannicksuc** [comment]
Oh ! It can be the problem, I will check it as soon as I can.
I have just tested with a smaller one and it does work.
Thanks.
